- name: Deploy Docker images to ECR and create/update Lambda functions
  hosts: localhost
  vars:
    aws_region: "us-west-2"
    ecr_repository_name: "traffic-simulation-lambda-repo"
    aws_account_id: "{{ lookup('env', 'AWS_ACCOUNT_ID') }}"
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"

  tasks:
    - name: Authenticate Docker to ECR
      shell: aws ecr get-login-password --region {{ aws_region }} | docker login --username AWS --password-stdin {{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
      register: ecr_login

    - name: Build and tag Docker images for each Lambda function
      loop:
        - { name: "trajectory", tag: "trajectory" }
        - { name: "lights", tag: "lights" }
        - { name: "roadValidation", tag: "roadValidation" }
        - { name: "stateDump", tag: "stateDump" }
      block:
        - name: Build Docker image
          docker_image:
            name: "{{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com/{{ ecr_repository_name }}:{{ item.tag }}"
            build: .
            tag: "{{ item.tag }}"
            buildargs:
              LAMBDA_FILE: "{{ item.name }}"
          when: ecr_login is succeeded

        - name: Push Docker image to ECR
          docker_image:
            name: "{{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com/{{ ecr_repository_name }}:{{ item.tag }}"
            push: yes
          when: ecr_login is succeeded

    - name: Create or update Lambda functions with ECR images
      loop:
        - { function_name: "trajectory", tag: "trajectory", env_vars: { DYNAMODB_TABLE: "TrafficSimulation", VEHICLE_TRAJECTORY_QUEUE: "VehicleTrajectoryQueue" } }
        - { function_name: "lights", tag: "lights", env_vars: { DYNAMODB_TABLE: "TrafficSimulation", TRAFFIC_LIGHT_QUEUE: "TrafficLightQueue" } }
        - { function_name: "roadValidation", tag: "roadValidation", env_vars: { DYNAMODB_TABLE: "TrafficSimulation" } }
        - { function_name: "stateDump", tag: "stateDump", env_vars: { DYNAMODB_TABLE: "TrafficSimulation" } }
      aws_lambda:
        name: "{{ item.function_name }}"
        role: "arn:aws:iam::{{ aws_account_id }}:role/LambdaExecutionRole"
        package_type: "Image"
        image_uri: "{{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com/{{ ecr_repository_name }}:{{ item.tag }}"
        memory_size: 128
        timeout: 30
        environment_variables: "{{ item.env_vars }}"
        state: present
        region: "{{ aws_region }}"
      environment:
        AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"
