---
- name: Deploy Lambda Functions and API Gateway
  hosts: localhost
  connection: local
  vars:
    aws_region: "us-east-2"
    aws_account_id: "{{ lookup('env', 'AWS_ACCOUNT_ID') }}"
    ecr_repository: "{{ lookup('env', 'ECR_REPOSITORY') }}"
    image_tag: "{{ lookup('env', 'GITHUB_SHA') }}"
    lambda_functions:
      - name: 'trajectory'
        tag: 'trajectory'
      - name: 'lights'
        tag: 'lights'
      - name: 'roadValidation'
        tag: 'roadValidation'
      - name: 'stateDump'
        tag: 'stateDump'

  tasks:
    - name: Create or update Lambda functions
      aws_lambda:
        state: present
        name: "{{ item.name }}"
        image_uri: "{{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com/{{ ecr_repository }}:{{ item.tag }}-{{ image_tag }}"
        role: "arn:aws:iam::{{ aws_account_id }}:role/LambdaExecutionRole"
      loop: "{{ lambda_functions }}"

    - name: Create API Gateway
      aws_apigatewayv2:
        name: "StateDumpAPI"
        protocol_type: "HTTP"
        state: present
      register: apigw

    - name: Create API Gateway Integration
      aws_apigatewayv2_integration:
        api_id: "{{ apigw.api['ApiId'] }}"
        integration_type: "AWS_PROXY"
        integration_uri: "arn:aws:lambda:{{ aws_region }}:{{ aws_account_id }}:function:stateDump"
        payload_format_version: "2.0"
        state: present
      register: integration

    - name: Create API Gateway Route
      aws_apigatewayv2_route:
        api_id: "{{ apigw.api['ApiId'] }}"
        route_key: "GET /stateDump"
        target: "integrations/{{ integration.integration['IntegrationId'] }}"
        state: present

    - name: Deploy API
      aws_apigatewayv2_deployment:
        api_id: "{{ apigw.api['ApiId'] }}"
        description: "Initial deployment"
        state: present

    - name: Output API Endpoint
      debug:
        msg: "API Endpoint: {{ apigw.api['ApiEndpoint'] }}"
