name: CICD

on:
  push:
    branches:
      - main

jobs:
  provision-aws:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.7

      - name: Terraform Init with S3 backend
        run: |
          terraform init \
            -backend-config="bucket=mvilsoet-bucket" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}"
        working-directory: ./terraform

      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ./terraform

      - name: Terraform Plan
        id: plan
        run: terraform plan
        working-directory: ./terraform

      - name: Provision AWS resources
        id: apply
        run: terraform apply -auto-approve
        working-directory: ./terraform

      - name: Get ECR Repository Name
        id: ecr_output
        run: |
          echo "ECR_REPOSITORY=$(terraform output -raw ecr_repository_name)" >> $GITHUB_ENV
        working-directory: ./terraform

    outputs:
      ECR_REPOSITORY: ${{ steps.ecr_output.outputs.ECR_REPOSITORY }}

  build-and-push:
    needs: provision-aws
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lambda:
          - name: trajectory
            tag: trajectory
          - name: lights
            tag: lights
          - name: roadValidation
            tag: roadValidation
          - name: stateDump
            tag: stateDump

    env:
      AWS_REGION: us-west-2
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      ECR_REPOSITORY: ${{ needs.provision-aws.outputs.ECR_REPOSITORY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Build and push ${{ matrix.lambda.name }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ matrix.lambda.tag }}
          build-args: |
            LAMBDA_FILE=${{ matrix.lambda.name }}
          cache-from: type=gha,scope=my-lambda-caching-scope
          cache-to: type=gha,mode=max,scope=my-lambda-caching-scope
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.AWS_REGION }}

  deploy-ansible:
    needs: build-and-push
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-west-2
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ansible
        uses: ansible/ansible-setup-action@v2

      - name: Run Ansible Playbook to deploy to ECR and update Lambdas
        run: ansible-playbook ansible/playbook.yml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
