name: Setup ECR with Placeholder Images

on:
  workflow_dispatch:

jobs:
  setup-ecr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Check if ECR Repository exists
        id: ecr_repo
        run: |
          aws ecr describe-repositories --repository-names lambda_repository || \
          aws ecr create-repository --repository-name lambda_repository

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        with:
          aws-region: us-east-2

      - name: Build and Push AWS Lambda-Compatible Placeholder Images
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-2.amazonaws.com
          ECR_REPOSITORY: lambda_repository
        run: |
          # Build and tag the placeholder image for each Lambda function
          for lambda in calculator results; do
            IMAGE_TAG=$lambda
            docker build -f .github/Dockerfile.lambda-placeholder -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          done
